{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e014d869",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "========== Simple Calculator ==========\n",
      "You can perform: +  -  *  /\n",
      "Type 'q' at any time to quit.\n",
      "\n",
      " Result: 4.0 * 4.0 = 16.0\n",
      "\n",
      " Result: 5.0 + 9.0 = 14.0\n",
      "\n",
      " Result: 1.0 - 9.0 = -8.0\n",
      "\n",
      " Result: 5.0 / 8.0 = 0.625\n",
      "\n",
      " Invalid input. Please enter a valid number.\n",
      "\n",
      " Invalid input. Please enter a valid number.\n",
      "\n",
      "Exiting calculator. Goodbye!\n"
     ]
    }
   ],
   "source": [
    "# ==========================\n",
    "# Calculator Program (CLI)\n",
    "# ==========================\n",
    "\n",
    "# Define functions for each operation\n",
    "def add(a, b):\n",
    "    \"\"\"Return sum of a and b\"\"\"\n",
    "    return a + b\n",
    "\n",
    "def subtract(a, b):\n",
    "    \"\"\"Return a minus b\"\"\"\n",
    "    return a - b\n",
    "\n",
    "def multiply(a, b):\n",
    "    \"\"\"Return a times b\"\"\"\n",
    "    return a * b\n",
    "\n",
    "def divide(a, b):\n",
    "    \"\"\"Return a divided by b, handle division by zero\"\"\"\n",
    "    if b == 0:\n",
    "        return \"Error: Division by zero!\"\n",
    "    return a / b\n",
    "\n",
    "\n",
    "def calculator():\n",
    "    \"\"\"Main calculator loop\"\"\"\n",
    "    print(\"========== Simple Calculator ==========\")\n",
    "    print(\"You can perform: +  -  *  /\")\n",
    "    print(\"Type 'q' at any time to quit.\\n\")\n",
    "\n",
    "    while True:\n",
    "        # Take first input\n",
    "        num1_input = input(\"Enter first number (or 'q' to quit): \")\n",
    "        if num1_input.lower() == \"q\":\n",
    "            print(\"Exiting calculator. Goodbye!\")\n",
    "            break  # exit loop\n",
    "\n",
    "        # Validate and convert first number\n",
    "        try:\n",
    "            num1 = float(num1_input)\n",
    "        except ValueError:\n",
    "            print(\" Invalid input. Please enter a valid number.\\n\")\n",
    "            continue  # restart loop\n",
    "\n",
    "        # Take operator\n",
    "        op = input(\"Enter operator (+, -, *, /): \")\n",
    "        if op not in [\"+\", \"-\", \"*\", \"/\"]:\n",
    "            print(\" Invalid operator. Please enter one of +, -, *, /.\\n\")\n",
    "            continue\n",
    "\n",
    "        # Take second input\n",
    "        num2_input = input(\"Enter second number: \")\n",
    "        try:\n",
    "            num2 = float(num2_input)\n",
    "        except ValueError:\n",
    "            print(\" Invalid input. Please enter a valid number.\\n\")\n",
    "            continue\n",
    "\n",
    "        # Perform operation based on operator\n",
    "        if op == \"+\":\n",
    "            result = add(num1, num2)\n",
    "        elif op == \"-\":\n",
    "            result = subtract(num1, num2)\n",
    "        elif op == \"*\":\n",
    "            result = multiply(num1, num2)\n",
    "        elif op == \"/\":\n",
    "            result = divide(num1, num2)\n",
    "\n",
    "        # Print result\n",
    "        print(f\" Result: {num1} {op} {num2} = {result}\\n\")\n",
    "\n",
    "\n",
    "# Run calculator only if this file is executed directly\n",
    "if __name__ == \"__main__\":\n",
    "    calculator()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4311df8d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
